package meta.works.zim.annotationhelper;

import java.util.UUID;

public
enum ZimPageNameStrategy
{
	TTT,
	AGENDA31,
	ANARCHOCHRISTIAN,
	BIT_ONE_IS_EPISODE_NUMBER,
	BIT_TWO_IS_EPISODE_NUMBER,
	BIT_THREE_IS_EPISODE_NUMBER,
	FUSE_TWO,
	GWO,
	SEASON_2_EPISODE_4,
	USER_ERROR_DIAMOND_COLLECTION,
	BEST_EFFORT,
	CSWDC,
	MartinHash,
	FTL,
	BillBurr,
	LIBERTARIAN_CHRISTIAN,
	LIBERTY_WEEKLY,
	JORDAN_PETERSON,
	UUID
	,
}
